//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.25 at 04:49:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "persistence.carto.legend.renderer.core.orbisgis.org")
package org.orbisgis.core.renderer.legend.carto.persistence;
