//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.25 at 04:49:43 PM CEST 
//


package org.orbisgis.core.layerModel.persistence;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{persistence.layerModel.core.orbisgis.org}idTime"/>
 *         &lt;element ref="{persistence.layerModel.core.orbisgis.org}boundingBox"/>
 *         &lt;element ref="{persistence.layerModel.core.orbisgis.org}abstract-layer" maxOccurs="unbounded"/>
 *         &lt;element ref="{persistence.layerModel.core.orbisgis.org}selected-layer" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idTime",
    "boundingBox",
    "abstractLayer",
    "selectedLayer"
})
@XmlRootElement(name = "map-context")
public class MapContext {

    @XmlElement(required = true)
    protected IdTime idTime;
    @XmlElement(required = true)
    protected BoundingBox boundingBox;
    @XmlElement(name = "abstract-layer", required = true)
    protected List<AbstractLayerType> abstractLayer;
    @XmlElement(name = "selected-layer", required = true)
    protected List<SelectedLayer> selectedLayer;

    /**
     * Gets the value of the idTime property.
     * 
     * @return
     *     possible object is
     *     {@link IdTime }
     *     
     */
    public IdTime getIdTime() {
        return idTime;
    }

    /**
     * Sets the value of the idTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdTime }
     *     
     */
    public void setIdTime(IdTime value) {
        this.idTime = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link BoundingBox }
     *     
     */
    public BoundingBox getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoundingBox }
     *     
     */
    public void setBoundingBox(BoundingBox value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the abstractLayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractLayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractLayerType }
     * 
     * 
     */
    public List<AbstractLayerType> getAbstractLayer() {
        if (abstractLayer == null) {
            abstractLayer = new ArrayList<AbstractLayerType>();
        }
        return this.abstractLayer;
    }

    /**
     * Gets the value of the selectedLayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedLayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedLayer }
     * 
     * 
     */
    public List<SelectedLayer> getSelectedLayer() {
        if (selectedLayer == null) {
            selectedLayer = new ArrayList<SelectedLayer>();
        }
        return this.selectedLayer;
    }

}
