//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.25 at 04:49:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "persistence.layerModel.core.orbisgis.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.orbisgis.core.layerModel.persistence;
